### ISSUE TITLE
add minimal installation instructions

### ISSUE THREAD

**Issue by lclem** [alhassy/org-agda-mode#5]
how do we install/use `org-agda-mode`?
does it suffice to load `org-agda-mode.el`?
is `literate.el` needed?

thanks!

**Comment by armkeh** [comment]
`literate.el` was an old set of tools; I've removed that file to avoid confusion, and added the minimal installation instructions for `org-agda-mode.el` to the README.

**Comment by lclem** [comment]
great thanks!
